= Franklyn2
Birklbauer Jonas, Bojer Nico, Gahleitner Lorenz, Hosic Tarik
1.0, 2020-08-22
ifndef::sourcedir[:sourcedir: ../src/main/java]
ifndef::imagesdir[:imagesdir: images]
ifndef::backend[:backend: html5]
:icons: font

== Ausgangssituation
Die HTL Leonding ist eine HTL im Zentralraum von Oberösterreich.

Für Tests und Schularbeiten am PC wurde Franklyn benutzt, um Professoren die Hilfe für Schüler zu erleichtern und eine gerechtere Umgebung zu schaffen.

== Problemstellung
- die Libraries von Franklyn sind einige Jahre veraltet,
- es ist sehr einseitig gestaltet, nachdem die Schüler in dem Client keinerlei Hilfe anfordern können.


== Ist-Zustand
- Franklyn2 mit aktualisierten Libraries,
- Aktualisierte Clients für Linux / Windows, Mac noch nicht kompatibel,
- Implementierte Sicherungsskripts für die Integration von Git, die noch nicht in den derzeitigen Clients vorhanden sind, da sie noch getestet werden.

=== Live Demo
- https://franklyn2.htl-leonding.ac.at[window=_blank]

== Was wird sein?
- Einbindung der Sicherungsskripts
- Client für Mac bereitstellen
- Aufzeige-Funktion für Schüler